node:
  switch01:
    mlag:
      address: 169.254.1.1/30
      backupip: 192.168.200.2
      members:
        - swp2
      peerip: 169.254.1.2
      sysmac: "44:38:39:FF:01:56"
      priority: 100
      interfaces:
        bond01:
          clagid: "1"
          members: swp1
          mode: access
          vlans: "100"
    overlay:
      anycastip:
      vxlan:
        vni:
          vlan:
    ports:
      - swp1
      - swp2
    lacp:
      interfaces:
        members:
    switching:
      bridge:
        - bond01
        - peerlink
      interfaces:
        switchport:
          mode:
          vlans:
      vlans:
        - 100
    routing:
      lo:
      ospf:
        area:
        neighbors:
      bgp:
        asn:
        underlay:
          external:
            peers:
          internal:
            peers:
      svi:
        vlan100:
          ip: 172.16.121.2/24
          vlan: 100
          vrrp:
            mac: "44:38:39:FF:00:01"
            ip: 172.16.121.1/24
  switch02:
    mlag:
      address: 169.254.1.2/30
      backupip: 192.168.200.1
      members:
      - swp2
      peerip: 169.254.1.1
      sysmac: "44:38:39:FF:01:56"
      priority: 100
      interfaces:
        bond01:
          clagid: 1
          members: swp1
          mode: access
          vlans: "100"
    overlay:
      anycastip:
      vxlan:
        vni:
          vlan:
    ports:
      - swp1
      - swp2
    lacp:
      interfaces:
        members:
    switching:
      bridge:
        - bond01
        - peerlink
      interfaces:
        switchport:
          mode:
          vlans:
      vlans:
        - 100
    routing:
      lo:
      ospf:
        area:
        neighbors:
      bgp:
        asn:
        underlay:
          external:
            peers:
          internal:
            peers:
      svi:
        vlan100:
          ip: 172.16.121.3/24
          vlan: 100
          vrrp:
            mac: "44:38:39:FF:00:01"
            ip: 172.16.121.1/24
